const LOCAL_STORAGE_ACCESS_TOKEN_KEY = "accessToken";
const LOCAL_STORAGE_REFRESH_TOKEN_KEY = "refreshToken";

export const Constants = {
  LOCAL_STORAGE_ACCESS_TOKEN_KEY,
  LOCAL_STORAGE_REFRESH_TOKEN_KEY,
  WMATIC_CURRENCY_ADDRESS: "0x9c3C9283D3e44854697Cd22D3Faa240Cfb032889",
  FEE_COLLECT_MODULE: "FeeCollectModule",
};
