const SESSION_STORAGE_ACCESS_TOKEN_KEY = "accessToken"
const SESSION_STORAGE_REFRESH_TOKEN_KEY = "refreshToken"

export const Constants = {
    SESSION_STORAGE_ACCESS_TOKEN_KEY,
    SESSION_STORAGE_REFRESH_TOKEN_KEY
}